use eslint instead of tslint
sxyz-edu/user-scripts pull request #14
Opened 2019-07-18 12:18 UTC by swwind

fix #13

2019-07-18 13:32 UTC, sxyugao commented
Why not unify the indentation style of .eslintrc?

2019-07-18 23:47 UTC, sxyugao requested changes
Why not unify the indentation style of .eslintrc?

2019-07-19 03:00 UTC, swwind commented
我还感觉应该加一些测试？

2019-07-19 12:22 UTC, sxyugao commented
> 我还感觉应该加一些测试？

比如？

2019-07-24 11:45 UTC, sxyugao approved these changes

2019-07-24 11:49 UTC, merged